<a href="https://colab.research.google.com/github/Satyajit99p/online-auction-fraud-detection/blob/master/Copy_of_Trial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import os
os.getcwd()

'/content'

In [4]:
os.chdir('/content/drive/My Drive/online auction fraud detection')

PREPROCESSING


In [5]:
import pandas as pd
import numpy as np
import seaborn as sb

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [6]:
data=pd.read_csv('Online Auction_Shill Bidding Dataset.csv')

In [7]:
data.describe()

Record_ID   Auction_ID  ...  Auction_Duration        Class
count   6321.000000  6321.000000  ...       6321.000000  6321.000000
mean    7535.829457  1241.388230  ...          4.615093     0.106787
std     4364.759137   735.770789  ...          2.466629     0.308867
min        1.000000     5.000000  ...          1.000000     0.000000
25%     3778.000000   589.000000  ...          3.000000     0.000000
50%     7591.000000  1246.000000  ...          5.000000     0.000000
75%    11277.000000  1867.000000  ...          7.000000     0.000000
max    15144.000000  2538.000000  ...         10.000000     1.000000

[8 rows x 12 columns]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6321 entries, 0 to 6320
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Record_ID               6321 non-null   int64  
 1   Auction_ID              6321 non-null   int64  
 2   Bidder_ID               6321 non-null   object 
 3   Bidder_Tendency         6321 non-null   float64
 4   Bidding_Ratio           6321 non-null   float64
 5   Successive_Outbidding   6321 non-null   float64
 6   Last_Bidding            6321 non-null   float64
 7   Auction_Bids            6321 non-null   float64
 8   Starting_Price_Average  6321 non-null   float64
 9   Early_Bidding           6321 non-null   float64
 10  Winning_Ratio           6321 non-null   float64
 11  Auction_Duration        6321 non-null   int64  
 12  Class                   6321 non-null   int64  
dtypes: float64(8), int64(4), object(1)
memory usage: 642.1+ KB


In [9]:
data.head(10)

Record_ID  Auction_ID Bidder_ID  ...  Winning_Ratio  Auction_Duration  Class
0          1         732     _***i  ...       0.666667                 5      0
1          2         732     g***r  ...       0.944444                 5      0
2          3         732     t***p  ...       1.000000                 5      0
3          4         732     7***n  ...       1.000000                 5      0
4          5         900     z***z  ...       0.500000                 7      0
5          8         900     i***e  ...       0.800000                 7      0
6         10         900     m***p  ...       0.750000                 7      0
7         12         900     k***a  ...       1.000000                 7      1
8         13        2370     g***r  ...       0.944444                 7      1
9         27         600     e***t  ...       0.611111                 7      1

[10 rows x 13 columns]

In [10]:
data.shape

(6321, 13)

In [11]:
df=data.iloc[:,3:]
type(df)

pandas.core.frame.DataFrame

In [12]:
df.shape

(6321, 10)

In [13]:
df.head(10)

Bidder_Tendency  Bidding_Ratio  ...  Auction_Duration  Class
0         0.200000       0.400000  ...                 5      0
1         0.024390       0.200000  ...                 5      0
2         0.142857       0.200000  ...                 5      0
3         0.100000       0.200000  ...                 5      0
4         0.051282       0.222222  ...                 7      0
5         0.038462       0.111111  ...                 7      0
6         0.400000       0.222222  ...                 7      0
7         0.137931       0.444444  ...                 7      1
8         0.121951       0.185185  ...                 7      1
9         0.155172       0.346154  ...                 7      1

[10 rows x 10 columns]

In [14]:
# Data is preprocessed
# As there is a classification issue addressed, outliers are not present.
# There is no missing values and all rows contain polished data.
# 'Record_ID','Auction_ID','Bidder_ID' are non-influential in determing the desired classification.so they are omitted.

MODEL CREATION AND TRAINING

In [15]:
import tensorflow as tf
import keras
from keras.callbacks import *

In [16]:
features=df.iloc[:,:9]
labels=df.iloc[:,-1]

print(features.shape)
print(labels.shape)

(6321, 9)
(6321,)


In [17]:
from sklearn.model_selection import train_test_split

x_train_full,x_test,y_train_full,y_test=train_test_split(features,labels,random_state=9)
x_train,x_valid,y_train,y_valid=train_test_split(x_train_full,y_train_full,random_state=9)

In [18]:
x_train.shape

(3555, 9)

In [19]:
y_train.shape

(3555,)

In [20]:
x_test.shape

(1581, 9)

In [21]:
y_test.shape

(1581,)

In [22]:
x_valid.shape

(1185, 9)

In [23]:
y_valid.shape

(1185,)

In [24]:
# there is consistent division of the dataset into the training testing and validation biparts
# 3555+1581+1185=6321

In [25]:
np.random.seed(42)
tf.random.set_seed(42)

In [26]:
from sklearn.metrics import confusion_matrix

**SEQUENTIAL MODEL**

In [27]:
model=keras.models.Sequential([
                               keras.layers.Dense(60,kernel_initializer='uniform',activation='relu',input_shape=[9]),
                               keras.layers.Dense(60,kernel_initializer='uniform',activation='relu'),
                               keras.layers.Dense(1,activation='sigmoid')
])

In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 60)                600       
_________________________________________________________________
dense_1 (Dense)              (None, 60)                3660      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 61        
Total params: 4,321
Trainable params: 4,321
Non-trainable params: 0
_________________________________________________________________


In [29]:
model.compile(optimizer='adam',
              loss='mean_squared_error',
              metrics=['accuracy'])

In [30]:
checkpoint=keras.callbacks.ModelCheckpoint('best-Model.h5',save_best_only=True)
early=keras.callbacks.EarlyStopping(patience=20,restore_best_weights=True)

In [31]:
model.fit(x_train,y_train,epochs=200,batch_size=10,validation_data=(x_valid,y_valid),callbacks=[checkpoint,early])

Epoch 1/200
356/356 [==============================] - 1s 4ms/step - loss: 0.0570 - accuracy: 0.9446 - val_loss: 0.0165 - val_accuracy: 0.9688
Epoch 2/200
356/356 [==============================] - 1s 4ms/step - loss: 0.0160 - accuracy: 0.9781 - val_loss: 0.0152 - val_accuracy: 0.9789
Epoch 3/200
356/356 [==============================] - 1s 4ms/step - loss: 0.0160 - accuracy: 0.9761 - val_loss: 0.0139 - val_accuracy: 0.9747
Epoch 4/200
356/356 [==============================] - 1s 4ms/step - loss: 0.0142 - accuracy: 0.9781 - val_loss: 0.0170 - val_accuracy: 0.9738
Epoch 5/200
356/356 [==============================] - 1s 4ms/step - loss: 0.0140 - accuracy: 0.9800 - val_loss: 0.0156 - val_accuracy: 0.9772
Epoch 6/200
356/356 [==============================] - 1s 4ms/step - loss: 0.0128 - accuracy: 0.9823 - val_loss: 0.0147 - val_accuracy: 0.9772
Epoch 7/200
356/356 [==============================] - 1s 4ms/step - loss: 0.0118 - accuracy: 0.9823 - val_loss: 0.0157 - val_accuracy: 0.9764

In [32]:
trial=keras.models.load_model('best-Model.h5')

In [33]:
test=model.evaluate(x_test,y_test)

50/50 [==============================] - 0s 2ms/step - loss: 0.0043 - accuracy: 0.9943


In [34]:
y_pred=model.predict(x_test)

In [41]:
print(type(y_test))
print(type(y_pred))

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


In [38]:
y_test.values

array([0, 1, 0, ..., 0, 0, 0])

In [40]:
y_pred

array([[7.3043405e-10],
       [9.9742717e-01],
       [4.3093823e-05],
       ...,
       [1.8646462e-08],
       [6.6379036e-10],
       [4.6614264e-08]], dtype=float32)

In [42]:
y_pred=np.where(y_pred>=0.5,1,0)

In [48]:
y_pred=y_pred.flatten()

In [49]:
y_pred

array([0, 1, 0, ..., 0, 0, 0])

In [50]:
confusion_matrix(y_test,y_pred)

array([[1397,    4],
       [   5,  175]])

In [51]:
keras.backend.clear_session()

In [52]:
del model

FUNCTIONAL MODEL

In [76]:
input1=keras.layers.Input(shape=x_train.shape[1:])
hidden1=keras.layers.Dense(60,kernel_initializer='uniform',activation='relu')(input1)
hidden2=keras.layers.Dense(60,kernel_initializer='uniform',activation='relu')(hidden1)
concat=keras.layers.concatenate([input1,hidden2])
output=keras.layers.Dense(1,activation='sigmoid')(concat)
model=keras.models.Model(inputs=[input1],outputs=[output])

In [77]:
model.summary()

Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 9)]          0                                            
__________________________________________________________________________________________________
dense (Dense)                   (None, 60)           600         input_1[0][0]                    
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 60)           3660        dense[0][0]                      
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 69)           0           input_1[0][0]                    
                                                                 dense_1[0][0]         

In [78]:
model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['accuracy'])

In [79]:
checkpoint=keras.callbacks.ModelCheckpoint('best-Model.h5',save_best_only=True)
early=keras.callbacks.EarlyStopping(patience=20,restore_best_weights=True)

In [80]:
model.fit(x_train,y_train,epochs=200,batch_size=10,validation_data=(x_valid,y_valid),callbacks=[checkpoint,early])

Epoch 1/200
356/356 [==============================] - 2s 4ms/step - loss: 0.0791 - accuracy: 0.8878 - val_loss: 0.0174 - val_accuracy: 0.9671
Epoch 2/200
356/356 [==============================] - 1s 4ms/step - loss: 0.0177 - accuracy: 0.9764 - val_loss: 0.0150 - val_accuracy: 0.9814
Epoch 3/200
356/356 [==============================] - 1s 4ms/step - loss: 0.0181 - accuracy: 0.9738 - val_loss: 0.0137 - val_accuracy: 0.9806
Epoch 4/200
356/356 [==============================] - 1s 4ms/step - loss: 0.0158 - accuracy: 0.9758 - val_loss: 0.0185 - val_accuracy: 0.9738
Epoch 5/200
356/356 [==============================] - 1s 4ms/step - loss: 0.0162 - accuracy: 0.9767 - val_loss: 0.0164 - val_accuracy: 0.9764
Epoch 6/200
356/356 [==============================] - 1s 4ms/step - loss: 0.0159 - accuracy: 0.9783 - val_loss: 0.0143 - val_accuracy: 0.9772
Epoch 7/200
356/356 [==============================] - 1s 4ms/step - loss: 0.0144 - accuracy: 0.9792 - val_loss: 0.0164 - val_accuracy: 0.9747

In [81]:
trial=keras.models.load_model('best-Model.h5')

In [82]:
test=model.evaluate(x_test,y_test)

50/50 [==============================] - 0s 2ms/step - loss: 0.0035 - accuracy: 0.9962


In [83]:
print(type(y_pred))
print(type(y_test))

<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [84]:
y_pred

array([0, 1, 0, ..., 0, 0, 0])

In [85]:
y_test.values

array([0, 1, 0, ..., 0, 0, 0])

In [86]:
confusion_matrix(y_test,y_pred)

array([[1397,    4],
       [   5,  175]])

In [87]:
keras.backend.clear_session()

In [88]:
del model